language: c
matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
    env:
    - USE_BLAS=ON
    sudo: required
  - os: linux
    dist: trusty
    env:
    - USE_BLAS=OFF
    - USE_STATIC=ON
    sudo: required
  - os: linux
    dist: trusty
    env:
    - USE_BLAS=OFF
    - USE_STATIC=OFF
    sudo: required

before_install:
- sudo apt-get -qq install -y gfortran
- sudo apt-get -qq install -y make
- sudo apt-get -qq install -y cmake
- if [ "$USE_BLAS" = "ON" ]; then sudo apt-get -qq install -y libatlas-base-dev
    ; sudo apt-get -qq install -y libblas-dev
    ; sudo apt-get -qq install -y liblapack-dev
  ; fi
- export FC=`which gfortran`
- $FC --version

script:
- cmake . -DUSE_BLAS=${USE_BLAS} -DUSE_STATIC=${USE_STATIC}
- make -j$(nproc)

after_success:
- for i in BlasBit*; do echo $i
    ; ./$i
    ; echo ""
  ; done
- echo "DONE!"
