language: c
matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
    env:
    - MATH=BLAS
    sudo: required
  - os: linux
    dist: trusty
    env:
    - MATH=ATLAS
    sudo: required
  - os: linux
    dist: trusty
    env:
    - MATH=OPENBLAS
    sudo: required
  - os: linux
    dist: trusty
    env:
    - MATH=NONE
    - USE_STATIC=ON
    sudo: required
  - os: linux
    dist: trusty
    env:
    - MATH=NONE
    - USE_STATIC=OFF
    sudo: required
  - os: linux
    dist: xenial
    env:
    - MATH=BLAS
    sudo: required
  - os: linux
    dist: xenial
    env:
    - MATH=ATLAS
    sudo: required
  - os: linux
    dist: xenial
    env:
    - MATH=OPENBLAS
    sudo: required
  - os: linux
    dist: xenial
    env:
    - MATH=NONE
    - USE_STATIC=ON
    sudo: required
  - os: linux
    dist: xenial
    env:
    - MATH=NONE
    - USE_STATIC=OFF
    sudo: required
  - os: linux
    dist: bionic
    env:
    - MATH=BLAS
    sudo: required
  - os: linux
    dist: bionic
    env:
    - MATH=ATLAS
    sudo: required
  - os: linux
    dist: bionic
    env:
    - MATH=OPENBLAS
    sudo: required
  - os: linux
    dist: bionic
    env:
    - MATH=NONE
    - USE_STATIC=ON
    sudo: required
  - os: linux
    dist: bionic
    env:
    - MATH=NONE
    - USE_STATIC=OFF
    sudo: required

before_install:
- sudo apt-get -qq install -y gfortran
- sudo apt-get -qq install -y make
- sudo apt-get -qq install -y cmake
- if [ "$MATH" = "BLAS" ]; then sudo apt-get -qq install -y libblas-dev
  ; export USE_BLAS=ON
  ; fi
- if [ "$MATH" = "ATLAS" ]; then sudo apt-get -qq install -y libatlas-base-dev
  ; export USE_BLAS=ON
  ; fi
- if [ "$MATH" = "OPENBLAS" ]; then sudo apt-get -qq install -y libopenblas-dev
  ; export USE_BLAS=ON
  ; fi
- if [ "$MATH" = "NONE" ]; then export USE_BLAS=OFF ; fi
- export FC=`which gfortran`
- $FC --version

script:
- cmake . -DUSE_BLAS=${USE_BLAS} -DUSE_STATIC=${USE_STATIC}
- make -j$(nproc)

after_success:
- for i in BlasBit*; do echo $i
    ; ./$i
    ; echo ""
  ; done
- echo "DONE!"
